### ISSUE TITLE
Divide Our Projects and Student project in menu bar  

### ISSUE THREAD

**Issue by khinezarthwe** [khinezarthwe/mmdt_web_app#27]
example : 
![telegram-cloud-photo-size-5-6098206257665128533-x](https://github.com/khinezarthwe/mmdt_web_app/assets/5201124/b703dca5-081a-4481-9bf0-6b9fbd4a9b94)

**Comment by khinezarthwe** [comment]
https://github.com/khinezarthwe/mmdt_web_app/pull/30/files

**Comment by lavish-github** [comment]
Hey @khinezarthwe, the screenshot of the issue is not visible and it is showing that access is denied for the respective file.
![image](https://github.com/khinezarthwe/mmdt_web_app/assets/140691026/3d0a3700-3c84-4b38-975d-7c4508e236da)

Can you kindly provide some reference about issue, so that I can work on it? Thanks

**Comment by khinezarthwe** [comment]
We have already developed
